### ISSUE TITLE
Minor - bash subcommands replace makefile

### ISSUE THREAD

**Issue by ghost** [basvandijk/nixtodo#1]
I have used a makefile similarly in the past. I am leaning towards using a bash command with subcommands that correspond to each target in my next project, probably named "go"

**Comment by basvandijk** [comment]
Yes, that will also work I guess.

One advantage of Makefiles is that it handles dependencies well. Although in nixtodo I don't use that feature.

At work we switched from a Makefile to a Haskell program because that is easier to maintain. I talked about it briefly at NixCon:

https://www.youtube.com/watch?v=J4DgATIjx9E&t=747s

**Comment by ghost** [comment]
I must have missed that segment, will watch again... I usually use a Bash script or Makefile as an attempt to have all devs who might not know Haskell also be able to read/contribute.
